apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-registry.fullname" . }}
  labels:
    {{- include "private-registry.labels" . | nindent 4 }}
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      {{- if .Values.http.tls.enabled }}
      tls:
        certificate: /certs/tls.crt
        key: /certs/tls.key
      {{- end }}
    {{- if .Values.auth.enabled }}
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    {{- end }}
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    {{- with .Values.extraConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
