{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "private-registry.authSecretName" . }}
  labels:
    {{- include "private-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: {{ .Values.auth.htpasswd | quote }}
{{- end }}
